services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    environment:
      client_max_body_size: 10G
      global_max_body_size: 10G
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: nextcloud-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - nextcloud_network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: mariadb:11.4.5-ubi9
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=[senha]
      - MYSQL_PASSWORD=[senha]
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  collabora:
    container_name: collabora
    image: collabora/code:latest
    restart: always
    expose:
      - '9980'
    cap_add:
      - MKNOD
    environment:
      - domain=[domain]\\.com\\.br
      - VIRTUAL_HOST=office.[domain].com.br
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=office.[domain].com.br
      - LETSENCRYPT_EMAIL=marcio@[domain].com.br
      - dictionaries=pt_BR
    networks:
      - nextcloud_network

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    expose:
      - '80'
      - '9000'
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./opcache-recommed.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
      - ./scripts:/var/scripts
    environment:
      - REDIS_HOST=redis
      - VIRTUAL_HOST=nx.[domain].com.br
      - LETSENCRYPT_HOST=[domain].com.br
      - LETSENCRYPT_EMAIL=marcio@[domain].com.br
    restart: unless-stopped

volumes:
  document_data:
  document_log:
  nextcloud:
  db:

networks:
  nextcloud_network:
